# Generated by Django 5.1.7 on 2025-10-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0025_hackathonjudge_remove_neoproject_owner_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hackathonmentorlink",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sharxathon",
            name="judges",
        ),
        migrations.RemoveField(
            model_name="sharxathon",
            name="mentors",
        ),
        migrations.RemoveField(
            model_name="hackathonmentorlink",
            name="mentor",
        ),
        migrations.DeleteModel(
            name="HackathonJudge",
        ),
        migrations.DeleteModel(
            name="HackathonMentor",
        ),
        migrations.DeleteModel(
            name="HackathonMentorLink",
        ),
    ]
